routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BackPanel\AdminController;
use App\Http\Controllers\BackPanel\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    return view('home');
});

// Route::get('/index', function () {
//     return view('index');
// })->middleware(['auth', 'verified'])->name('index');

// Route::get('/about', function () {
//     return view('about');
// })->middleware(['auth', 'verified'])->name('about');


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::middleware('auth','role:admin')->group(function () {
    // Route::get('admin/dashboard', [AdminController::class, 'dashboard']);
    Route::get('admin/dashboard', [AdminController::class, 'dashboard'])->middleware('verified');
    Route::get('admin/facility', [AdminController::class, 'facility'])->name('admin.facility');
    Route::get('admin/booking', [AdminController::class, 'booking']);
    Route::get('admin/feedback', [AdminController::class, 'feedback']);
    Route::get('admin/users', [AdminController::class, 'user'])->name('admin.users');

    Route::delete('admin/users/delete', [AdminController::class, 'userdelete'])->name('users.destroy');
    Route::delete('admin/feedbacks/delete', [AdminController::class, 'feedbackdelete'])->name('feedback.destroy');
    Route::delete('admin/facility/delete', [AdminController::class, 'facilitydelete'])->name('facility.destroy');
    Route::post('admin/addfacility', [AdminController::class, 'addfacility'])->name('addfacility');
    Route::put('admin/facility/update/{id}', [AdminController::class, 'editfacility'])->name('facility.edit');
    Route::delete('admin/bookings/delete', [AdminController::class, 'bookingsdelete'])->name('bookings.destroy');

    Route::get('/bookings/chart', [AdminController::class, 'bookingsChart']);
    Route::get('/searchUsers', [AdminController::class, 'searchUsers'])->name('searchUsers');
    Route::get('/searchBookings', [AdminController::class, 'searchBookings'])->name('searchBookings');
    Route::get('/facilitystatus/{facilityId}', [AdminController::class, 'facilitystatus'])->name('facilitystatus');

});


Route::middleware('auth','role:user')->group(function () {
    Route::get('/index', [UserController::class, 'index'])->middleware('verified')->name('index');
    // Route::get('/home', [UserController::class, 'Dashboard'])->name('home');
    Route::get('/home', [UserController::class, 'Dashboard'])->middleware('verified')->name('home');
    Route::get('/about', [UserController::class, 'about'])->name('about');
    Route::get('/facilities', [UserController::class, 'Facility'])->name('facilities');
    Route::get('/bookings', [UserController::class, 'Bookings'])->name('bookings');
    Route::post('/home/feedback', [UserController::class, 'Feedback'])->name('feedback');
    Route::post('/facilities/addbooking', [UserController::class, 'addbooking'])->name('addbooking');
    Route::delete('/cancelbooking/{id}', [UserController::class, 'cancelbooking'])->name('cancelbooking');
    Route::get('/getTime/{subfacilityId}', [UserController::class, 'getTime'])->name('getTime');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'collegeid',
        'contact',
        'password',
    ];

    public function feedbacks() 
    {
        return $this->hasMany(Feedback::class, 'user_id');
    }
    public function bookings() 
    {
        return $this->hasMany(Booking::class, 'user_id');
    }

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function getInitialsAttribute()
    {
        $nameParts = explode(' ', $this->name);

        $firstNameInitial = strtoupper(substr($nameParts[0], 0, 1));
        $lastNameInitial = isset($nameParts[1]) ? strtoupper(substr($nameParts[1], 0, 1)) : '';

        return $firstNameInitial . $lastNameInitial;
    }
}

resources/views/include/MPH.blade.php
<div class="box">
    <div>
        <img src="{{ asset('asset/images/fbb.jpeg') }}" alt="Image 1">
    </div>
    <div class="s-text">
        <h3>Badminton</h3>
        <div class="line"></div>
        <p>MPH (badminton) can be booked from 10pm to 12pm and 9am to 10pm on weekdays and weekends respectively.</p>
        <div class="line"></div>
        <p>Max Booking hour: 1 hour</p>
        <button>Book Now</button>
    </div>
</div>
<div class="box">
    <div>
        <img src="asset/images/bb.jpeg" alt="Image 1">
    </div>              
    <div class="s-text">                
        <h3>Volleyball</h3>
        <div class="line"></div> 
        <p>MPH (volleyball) can be booked from 12pm to 10pm and 9am to 10pm on weekdays and weekends respectively.</p>
        <div class="line"></div> 
        <p>Max Booking hour: 1 hour</p>
    </div>         
</div>
<div class="box">
    <div>
        <img src="{{ asset('asset/images/fbb.jpeg') }}" alt="Image 1">
    </div>
    <div class="s-text">
        <h3>Table Tennis</h3>
        <div class="line"></div>
        <p>MPH (table tennis) can be booked from 10pm to 12pm and 9am to 10pm on weekdays and weekends respectively.</p>
        <div class="line"></div>
        <p>Max Booking hour: 1 hour</p>
        <button>Book Now</button>
    </div>
</div>
<div class="box">
    <div>
        <img src="asset/images/bb.jpeg" alt="Image 1">
    </div>              
    <div class="s-text">                
        <h3>Basketball Court</h3>
        <div class="line"></div> 
        <p>MPH (table tennis) can be booked from 10pm to 12pm and 9am to 10pm on weekdays and weekends respectively.</p>
        <div class="line"></div> 
        <p>Max Booking hour: 2 hours</p>
    </div>         
</div>

resources/views/include/basketball.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>calender</title>
   <link rel="stylesheet" type="text/css" href="{{ asset('./asset/css/calendar.css')}}">
   <title></title>    
</head>
<body>
    <div class="bookings">
        <div class="list-group px-4">
            <a href="#" class="list-group-item list-group-item-action active text-center py-2" style="background-color:#183866; border:none;">Bookings available today!</a>
            <a href="#" class="list-group-item list-group-item-action">12 - 1 pm<button class="booking-btn float-end">Book Now</button></a>
            <a href="#" class="list-group-item list-group-item-action">1 - 2 pm<button class="booking-btn float-end">Book Now</button></a>
            <a href="#" class="list-group-item list-group-item-action">2 - 3 pm<button class="booking-btn float-end">Book Now</button></a>
            <a href="#" class="list-group-item list-group-item-action">3 - 4 pm<button class="booking-btn float-end">Book Now</button></a>
            <a href="#" class="list-group-item list-group-item-action">4 - 5 pm<button class="booking-btn float-end">Book Now</button></a>
            <a href="#" class="list-group-item list-group-item-action">5 - 6 pm<button class="booking-btn float-end">Book Now</button></a>
        </div>  
    </div> 
</body>
</html>

resources/views/include/calendar.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dynamic Calendar JavaScript | CodingNepal</title>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

    <link rel="stylesheet" type="text/css" href="{{ asset('./asset/css/calendar.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <div class="wrapper">
      <div class="calendar-head">
        <p class="current-date"></p>
        <div class="icons" style="border: 1px solid red">
          <i id="prev" class="bx bx-chevron-left"></i>
          <i id="next" class="bx bx-chevron-right"></i>
        </div>
    </div>
      <div class="calendar">
        <ul class="weeks">
          <li>Sun</li>
          <li>Mon</li>
          <li>Tue</li>
          <li>Wed</li>
          <li>Thu</li>
          <li>Fri</li>
          <li>Sat</li>
        </ul>
        <ul class="days"></ul>
      </div>
    </div>
    
  </body>

<script>
const daysTag = document.querySelector(".days"),
currentDate = document.querySelector(".current-date"),
prevNextIcon = document.querySelectorAll(".icons i");

// getting new date, current year and month
let date = new Date(),
currYear = date.getFullYear(),
currMonth = date.getMonth();

// storing full name of all months in array
const months = ["January", "February", "March", "April", "May", "June", "July",
              "August", "September", "October", "November", "December"];

const renderCalendar = () => {
    let firstDayofMonth = new Date(currYear, currMonth, 1).getDay(), // getting first day of month
    lastDateofMonth = new Date(currYear, currMonth + 1, 0).getDate(), // getting last date of month
    lastDayofMonth = new Date(currYear, currMonth, lastDateofMonth).getDay(), // getting last day of month
    lastDateofLastMonth = new Date(currYear, currMonth, 0).getDate(); // getting last date of previous month
    let liTag = "";

    for (let i = firstDayofMonth; i > 0; i--) { // creating li of previous month last days
        liTag += `<li class="inactive">${lastDateofLastMonth - i + 1}</li>`;
    }

    for (let i = 1; i <= lastDateofMonth; i++) { // creating li of all days of current month
        // adding active class to li if the current day, month, and year matched
        let isToday = i === date.getDate() && currMonth === new Date().getMonth() 
                     && currYear === new Date().getFullYear() ? "active" : "";
        liTag += `<li class="${isToday}">${i}</li>`;
    }

    for (let i = lastDayofMonth; i < 6; i++) { // creating li of next month first days
        liTag += `<li class="inactive">${i - lastDayofMonth + 1}</li>`
    }
    currentDate.innerText = `${months[currMonth]} ${currYear}`; // passing current mon and yr as currentDate text
    daysTag.innerHTML = liTag;
}
renderCalendar();

prevNextIcon.forEach(icon => { // getting prev and next icons
    icon.addEventListener("click", () => { // adding click event on both icons
        // if clicked icon is previous icon then decrement current month by 1 else increment it by 1
        currMonth = icon.id === "prev" ? currMonth - 1 : currMonth + 1;

        if(currMonth < 0 || currMonth > 11) { // if current month is less than 0 or greater than 11
            // creating a new date of current year & month and pass it as date value
            date = new Date(currYear, currMonth, new Date().getDate());
            currYear = date.getFullYear(); // updating current year with new date year
            currMonth = date.getMonth(); // updating current month with new date month
        } else {
            date = new Date(); // pass the current date as date value
        }
        renderCalendar(); // calling renderCalendar function
    });
});
  </script>
</html>

resources/views/include/fetures.blade.php
<section class="feature" id="feature">
    <div class="feature-text">
        <h2>Key Features</h2>
        <p>We offer the best Services !</p>
    </div>
    <div class="feature-content">
        <div class="keyfeatures">
            <div style="display: flex; flex-direction: row; margin:1rem 0rem">
                <div class="features-icon">
                    <i class="bx bxs-bell" style="background-color: #efca08"></i>
                </div>
                <div class="feature-t">
                    <h5>Notifications and Alerts</h5>
                    Receive alerts for booking approvals, rejections, or changes in booking status.
                </div>
            </div>
            <div style="display: flex; flex-direction: row; margin:1rem 0rem">
                <div class="features-icon">
                    <i class="bx bx-check" style="background-color: #f59131"></i>
                </div>
                <div class="feature-t">
                    <h5>User-Friendly Interface</h5>
                    Intuitive and easy-to-navigate user interface
                </div>
            </div>
            <div style="display: flex; flex-direction: row; margin:1rem 0rem">
                <div class="features-icon">
                    <i class="bx bxs-calendar" style="background-color: #f53d31"></i>
                </div>
                <div class="feature-t">
                    <h5>Facility Availability and Scheduling</h5>
                    Real-time availability display of facilities<br>
                        Select desired booking dates and times.
                </div>
            </div>
            <div style="display: flex; flex-direction: row; margin:1rem 0rem">
                <div class="features-icon">
                    <i class="bx bxs-message-dots" style="background-color: #2ec1ac"></i>
                </div>
                <div class="feature-t">
                    <h5>Feedback and Rating System</h5>
                    Provide feedback and ratings for facilities they have booked
                </div>
            </div>
            <div style="display: flex; flex-direction: row; margin:1rem 0rem">
                <div class="features-icon">
                    <i class="bx bx-refresh" style="background-color: #be2ec1"></i>
                </div>
                <div class="feature-t">
                    <h5 class="h5">Modifications and Cancellations</h5>
                    Easily cancel or modify their bookings within a specified timeframe
                </div>
            </div>          
        </div>
        <div >
            <img src="asset/images/pic.png" class="img-fluid">
        </div>
    </div>             
    
</section>

resources/views/include/footer.blade.php
<section >
    <div class="blockcode">       
      <footer class="page-footer">
        <div class="d-flex flex-column mx-auto" style="width: 100%">
          <div class="d-flex flex-wrap justify-content-between">
            <div>
              <a href="" class="d-flex align-items-center p-0 text-white">
                <img alt="logo" src="asset/images/GFBS..png" width="150px" />
              </a>
              <p class="list my-3 pt-4" style="max-width: 400px; color: white;">
                GCIT Facility Booking System is a comprehensive software solution designed to streamline and enhance 
                the process of booking various facilities within the Gyalpozhing College campus. 
              </p>
              <div class="footer-icons">
                <i class="bx bxl-facebook" ></i>
                <i class="bx bxl-instagram" ></i>
                <i class="bx bxl-youtube" ></i>
                <i class="bx bxl-twitter" ></i>
              </div>
            </div>
            <div>
              <p class="h5 mb-4" style="font-weight: 600; font-size: 20px; color: white;">Useful Links</p>
              <ul class="p-0" style="list-style: none; cursor: pointer; font-size:15px">
                <li class="list my-3">
                  <a  href="https://www.gcit.edu.bt/">Gyalpozhing College of Information Technology</a>
                </li>
                <li class="list my-3">
                  <a  href="https://www.citizenservices.gov.bt/g2cportal/ListOfLifeEventComponent">G2C Services</a>
                </li>
                <li class="list my-3">
                  <a  href="https://www.rub.edu.bt/">Royal University of Bhutan</a>
                </li>
                <li class="list my-3">
                  <a  href="http://www.education.gov.bt/">Ministry of Education</a></li>
              </ul>
            </div>
            <div>
              <p class="h5 mb-4" style="font-weight: 600; color: white;">Contact Us At</p>
              <ul class="p-0" style="list-style: none; cursor: pointer; font-size:15px">
                <li class="list my-3">
                  <i class='bx bxs-phone-call'></i>
                  <a  href="" style='padding-left:15px;'> + 975 17301649</a>
                </li>
                <li class="list my-3">
                  <i class='bx bxs-phone-call'></i>
                  <a  href="" style='padding-left:15px;'> + 975 17680509</a>
                </li>
                <li class="list my-3">
                  <i class='bx bxs-envelope'></i>
                  <a  href="" style='padding-left:15px;'> 12200092.gcit@rub.edu.bt</a>
                </li>
                <li class="list my-3">
                  <i class='bx bxs-envelope'></i>
                  <a  href="" style='padding-left:15px;'>12200056.gcit@rub.edu.bt</a>
                </li>
                <li class="list my-3" >
                  <i class='bx bxs-map'></i>
                  <a  href="" style='padding-left:15px;'>Chamjekha, Thimphu, Bhutan</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </section>

  <!-- <end section> -->
  <div class="end">
      <div class="last-text">
          Copyright © 4th year IT Group 9 2023. All Rights Reserved.
      </div>
    </div>

resources/views/include/navbar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>
    {{-- <nav class="navbar fixed-top navbar-expand-lg" style="padding-top: 0;">
        <div class="container-fluid" style="padding: 22px 15%;background-color: rgba(24, 56, 102, 0.7);backdrop-filter: blur(3px);transition: all .45s ease; background-color: #183866; border-bottom:2px solid #06224A">
            <a class="navbar-brand" href="/home">
                <img src="asset/images/GFBS..png">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 nbar">
                @if(Route::has('login'))
                @auth
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href='/home'>Home</a>
                    </li>
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href="/facilities">Facilities</a>
                    </li>
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href="/about">About</a>
                    </li>   
                </ul>
                <div class="d-flex ms-auto">
                    <button type="button" class="btn" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-html="true" data-bs-content="" id="popoverTrigger">
                        <i class="bx bxs-bell" style="font-size:25px; color:#F59131"></i>
                    </button>
                    
                    <div class="collapse navbar-collapse" id="navbarDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="profile-initial">{{ Auth::user()->initials }}</span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item"><i class="bx bxs-contact pe-1" style="color:#183866"></i>{{ Auth::user()->name }}</a></li>
                                    <li><a class="dropdown-item"><i class="bx bx-envelope pe-1" style="color:#183866"></i>{{ Auth::user()->email }}</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{{route('bookings')}}">My Bookings</a></li>                          
                                    <li><a class="dropdown-item" href="{{route('profile.edit')}}">
                                        {{ __('Profile') }}
                                    </a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="mb-2">    
                                        <form method="POST" action="{{ route('logout') }}">
                                            @csrf
                                            <a class="logout-btn" href="{{ route('logout')}}" onclick="event.preventDefault(); this.closest('form').submit();">Logout</a>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
               
            </div>
            @else 
            <a class="login-btn" href="{{route('login')}}">Sign In</a>
            <a class="register-btn" href="{{route('register')}}">Sign Up</a>
            @endauth
            @endif
        </div>
    </nav>

    <div id="popoverContent" style="display: none">
        <h6 class="fw-bold">Notifications</h6><hr>
        <ul class="list-unstyled">
            <li>The football ground booking for 5/5/2023 from 2 to    4 PM, has been cancelled and is now open for booking.</li><hr>
            <li>The basketball court booking for 5/5/2023 from 6  to 7 PM, has been cancelled and is now open for booking.</li><hr>
            <li>We're excited to introduce a new facility! Please take a look and explore.</li><hr>
            <li>The badminton court booking for 5/5/2023 from 6 to 7 PM has been cancelled and is now available for booking.</li><hr>
        </ul>
    </div> --}}

    <nav class="navbar navbar-expand-lg navbar-light p-0 fixed-top">
        <div class="container-fluid" style="padding:20px 15%;background-color: rgba(24, 56, 102, 0.7); border-bottom:2px solid #06224A">
            <a class="navbar-brand" href="/home">
                <img src="asset/images/GFBS..png">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 nbar">
                @if(Route::has('login'))
                @auth
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href='/home'>Home</a>
                    </li>
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href="/facilities">Facilities</a>
                    </li>
                    <li class="nav-item px-4 ">
                        <a class="nav-link n-item" style="color: white; font-weight: 700;" href="/about">About</a>
                    </li> 
                    
                    <li>
                        <button  class=" position-relative bg-transparent border-0 py-2 mx-3" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-html="true"  id="popoverTrigger">
                            <i class="bx bxs-bell" style="font-size:25px; color:#F59131"></i>
                            @php
                                $unreadCount = auth()->user()->unreadNotifications->count();
                            @endphp
                            @if ($unreadCount >= 0)
                            <span style="color: white; font-size:10px" class="position-absolute top-10 start-100 translate-middle px-1 bg-danger rounded-circle">
                                {{ $unreadCount }}
                            </span>
                            @endif
                        </button>
                    </li>
                    
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="profile-initial">{{ Auth::user()->initials }}</span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" ><i class="bx bxs-contact pe-1" style="color:#183866"></i>{{ Auth::user()->name }}</a></li>
                            <li><a class="dropdown-item" ><i class="bx bx-envelope pe-1" style="color:#183866"></i>{{ Auth::user()->email }}</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{route('bookings')}}" style="font-weight:600">My Bookings</a></li>                          
                            <li><a class="dropdown-item" href="{{route('profile.edit')}}" style="font-weight:600">
                                {{ __('Profile') }}
                            </a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li class="mb-2">    
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf
                                    <a class="logout-btn" href="{{ route('logout')}}" onclick="event.preventDefault(); this.closest('form').submit();">Logout</a>
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>    
            </div>  
            @else                      
                <a class="mx-2 login-btn" href="{{route('login')}}">Sign In</a>
                <a class="mx-2 register-btn" href="{{route('register')}}">Sign Up</a>            
            @endauth
            @endif 
        </div>
    </nav>
    <div class="overflow-auto" id="popoverContent" style="display: none">
        @auth
        <h6 class="fw-bold">Notifications</h6><hr>
            @foreach(auth()->user()->notifications as $notification)
                <div >
                    {{ $notification->data['message'] }}
                </div><hr>
            @endforeach
        @else
        <p>User not authenticated</p>
        @endauth
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <script>
        $(document).ready(function () {
            var currentPage = window.location.pathname;

            $('.navbar-nav .nav-link').each(function () {
                var pageHref = $(this).attr('href');

                if (currentPage === pageHref) {
                    $(this).addClass('active-page');
                }
            });

            var popoverTrigger = document.getElementById("popoverTrigger");
            var popoverContent = document.getElementById("popoverContent");

            var popover = new bootstrap.Popover(popoverTrigger, {
                content: popoverContent.innerHTML,
                html: true,
            });

            popoverTrigger.addEventListener("click", function () {
                popover.show();
            });

        });
    </script>
</body>
</html>